#!/bin/bash -eu
project_root="$(cd $(dirname ${BASH_SOURCE[0]}); pwd)"
source "$project_root/libexec/setup-env.sh"
groovy_bin="$(cd $groovy_home/../bin; pwd)"

cd $classpath_lib
$groovy_bin/groovyc \
  -cp "$classpath" \
  "CliConsoleReportWriter.groovy" \
  "CliCodeNarc.groovy"

jar cvf "CliConsoleReportWriter.jar" CliConsoleReportWriter*.class
jar cvf "CliCodeNarc.jar" CliCodeNarc*.class
