import org.codenarc.report.ReportWriter
import org.codenarc.AnalysisContext
import org.codenarc.results.Results
import org.fusesource.jansi.AnsiConsole;
import static org.fusesource.jansi.Ansi.*;
import static org.fusesource.jansi.Ansi.Color.*;


class CliConsoleReportWriter implements ReportWriter {
  int maxPriority = 3
  Map ruleToUrl = [
    AssertWithinFinallyBlock : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#AssertWithinFinallyBlock",
    AssignmentInConditional : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#AssignmentInConditional",
    BigDecimalInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#BigDecimalInstantiation",
    BitwiseOperatorInConditional : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#BitwiseOperatorInConditional",
    BooleanGetBoolean : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#BooleanGetBoolean",
    BrokenNullCheck : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#BrokenNullCheck",
    BrokenOddnessCheck : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#BrokenOddnessCheck",
    ClassForName : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#ClassForName",
    ComparisonOfTwoConstants : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#ComparisonOfTwoConstants",
    ComparisonWithSelf : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#ComparisonWithSelf",
    ConstantAssertExpression : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#ConstantAssertExpression",
    ConstantIfExpression : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#ConstantIfExpression",
    ConstantTernaryExpression : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#ConstantTernaryExpression",
    DeadCode : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#DeadCode",
    DoubleNegative : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#DoubleNegative",
    DuplicateCaseStatement : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#DuplicateCaseStatement",
    DuplicateMapKey : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#DuplicateMapKey",
    DuplicateSetValue : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#DuplicateSetValue",
    EmptyCatchBlock : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyCatchBlock",
    EmptyClass : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyClass",
    EmptyElseBlock : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyElseBlock",
    EmptyFinallyBlock : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyFinallyBlock",
    EmptyForStatement : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyForStatement",
    EmptyIfStatement : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyIfStatement",
    EmptyInstanceInitializer : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyInstanceInitializer",
    EmptyMethod : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyMethod",
    EmptyStaticInitializer : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyStaticInitializer",
    EmptySwitchStatement : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptySwitchStatement",
    EmptySynchronizedStatement : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptySynchronizedStatement",
    EmptyTryBlock : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyTryBlock",
    EmptyWhileStatement : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EmptyWhileStatement",
    EqualsAndHashCode : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EqualsAndHashCode",
    EqualsOverloaded : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#EqualsOverloaded",
    ExplicitGarbageCollection : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#ExplicitGarbageCollection",
    ForLoopShouldBeWhileLoop : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#ForLoopShouldBeWhileLoop",
    HardCodedWindowsFileSeparator : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#HardCodedWindowsFileSeparator",
    HardCodedWindowsRootDirectory : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#HardCodedWindowsRootDirectory",
    IntegerGetInteger : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#IntegerGetInteger",
    MultipleUnaryOperators : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#MultipleUnaryOperators",
    RandomDoubleCoercedToZero : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#RandomDoubleCoercedToZero",
    RemoveAllOnSelf : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#RemoveAllOnSelf",
    ReturnFromFinallyBlock : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#ReturnFromFinallyBlock",
    ThrowExceptionFromFinallyBlock : "http://codenarc.sourceforge.net/codenarc-rules-basic.html#ThrowExceptionFromFinallyBlock",
    ElseBlockBraces : "http://codenarc.sourceforge.net/codenarc-rules-braces.html#ElseBlockBraces",
    ForStatementBraces : "http://codenarc.sourceforge.net/codenarc-rules-braces.html#ForStatementBraces",
    IfStatementBraces : "http://codenarc.sourceforge.net/codenarc-rules-braces.html#IfStatementBraces",
    WhileStatementBraces : "http://codenarc.sourceforge.net/codenarc-rules-braces.html#WhileStatementBraces",
    BusyWait : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#BusyWait",
    DoubleCheckedLocking : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#DoubleCheckedLocking",
    InconsistentPropertyLocking : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#InconsistentPropertyLocking",
    InconsistentPropertySynchronization : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#InconsistentPropertySynchronization",
    NestedSynchronization : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#NestedSynchronization",
    StaticCalendarField : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#StaticCalendarField",
    StaticConnection : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#StaticConnection",
    StaticDateFormatField : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#StaticDateFormatField",
    StaticMatcherField : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#StaticMatcherField",
    StaticSimpleDateFormatField : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#StaticSimpleDateFormatField",
    SynchronizedMethod : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#SynchronizedMethod",
    SynchronizedOnBoxedPrimitive : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#SynchronizedOnBoxedPrimitive",
    SynchronizedOnGetClass : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#SynchronizedOnGetClass",
    SynchronizedOnReentrantLock : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#SynchronizedOnReentrantLock",
    SynchronizedOnString : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#SynchronizedOnString",
    SynchronizedOnThis : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#SynchronizedOnThis",
    SynchronizedReadObjectMethod : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#SynchronizedReadObjectMethod",
    SystemRunFinalizersOnExit : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#SystemRunFinalizersOnExit",
    ThisReferenceEscapesConstructor : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#ThisReferenceEscapesConstructor",
    ThreadGroup : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#ThreadGroup",
    ThreadLocalNotStaticFinal : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#ThreadLocalNotStaticFinal",
    ThreadYield : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#ThreadYield",
    UseOfNotifyMethod : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#UseOfNotifyMethod",
    VolatileArrayField : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#VolatileArrayField",
    VolatileLongOrDoubleField : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#VolatileLongOrDoubleField",
    WaitOutsideOfWhileLoop : "http://codenarc.sourceforge.net/codenarc-rules-concurrency.html#WaitOutsideOfWhileLoop",
    ConfusingTernary : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#ConfusingTernary",
    CouldBeElvis : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#CouldBeElvis",
    CouldBeSwitchStatement : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#CouldBeSwitchStatement",
    FieldTypeRequired : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#FieldTypeRequired",
    HashtableIsObsolete : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#HashtableIsObsolete",
    IfStatementCouldBeTernary : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#IfStatementCouldBeTernary",
    InvertedCondition : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#InvertedCondition",
    InvertedIfElse : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#InvertedIfElse",
    LongLiteralWithLowerCaseL : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#LongLiteralWithLowerCaseL",
    MethodParameterTypeRequired : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#MethodParameterTypeRequired",
    MethodReturnTypeRequired : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#MethodReturnTypeRequired",
    NoDef : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#NoDef",
    NoJavaUtilDate : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#NoJavaUtilDate",
    NoTabCharacter : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#NoTabCharacter",
    ParameterReassignment : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#ParameterReassignment",
    PublicMethodsBeforeNonPublicMethods : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#PublicMethodsBeforeNonPublicMethods",
    StaticFieldsBeforeInstanceFields : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#StaticFieldsBeforeInstanceFields",
    StaticMethodsBeforeInstanceMethods : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#StaticMethodsBeforeInstanceMethods",
    TernaryCouldBeElvis : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#TernaryCouldBeElvis",
    TrailingComma : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#TrailingComma",
    VariableTypeRequired : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#VariableTypeRequired",
    VectorIsObsolete : "http://codenarc.sourceforge.net/codenarc-rules-convention.html#VectorIsObsolete",
    AbstractClassWithPublicConstructor : "http://codenarc.sourceforge.net/codenarc-rules-design.html#AbstractClassWithPublicConstructor",
    AbstractClassWithoutAbstractMethod : "http://codenarc.sourceforge.net/codenarc-rules-design.html#AbstractClassWithoutAbstractMethod",
    AssignmentToStaticFieldFromInstanceMethod : "http://codenarc.sourceforge.net/codenarc-rules-design.html#AssignmentToStaticFieldFromInstanceMethod",
    BooleanMethodReturnsNull : "http://codenarc.sourceforge.net/codenarc-rules-design.html#BooleanMethodReturnsNull",
    BuilderMethodWithSideEffects : "http://codenarc.sourceforge.net/codenarc-rules-design.html#BuilderMethodWithSideEffects",
    CloneableWithoutClone : "http://codenarc.sourceforge.net/codenarc-rules-design.html#CloneableWithoutClone",
    CloseWithoutCloseable : "http://codenarc.sourceforge.net/codenarc-rules-design.html#CloseWithoutCloseable",
    CompareToWithoutComparable : "http://codenarc.sourceforge.net/codenarc-rules-design.html#CompareToWithoutComparable",
    ConstantsOnlyInterface : "http://codenarc.sourceforge.net/codenarc-rules-design.html#ConstantsOnlyInterface",
    EmptyMethodInAbstractClass : "http://codenarc.sourceforge.net/codenarc-rules-design.html#EmptyMethodInAbstractClass",
    FinalClassWithProtectedMember : "http://codenarc.sourceforge.net/codenarc-rules-design.html#FinalClassWithProtectedMember",
    ImplementationAsType : "http://codenarc.sourceforge.net/codenarc-rules-design.html#ImplementationAsType",
    Instanceof : "http://codenarc.sourceforge.net/codenarc-rules-design.html#Instanceof",
    LocaleSetDefault : "http://codenarc.sourceforge.net/codenarc-rules-design.html#LocaleSetDefault",
    NestedForLoop : "http://codenarc.sourceforge.net/codenarc-rules-design.html#NestedForLoop",
    PrivateFieldCouldBeFinal : "http://codenarc.sourceforge.net/codenarc-rules-design.html#PrivateFieldCouldBeFinal",
    PublicInstanceField : "http://codenarc.sourceforge.net/codenarc-rules-design.html#PublicInstanceField",
    ReturnsNullInsteadOfEmptyArray : "http://codenarc.sourceforge.net/codenarc-rules-design.html#ReturnsNullInsteadOfEmptyArray",
    ReturnsNullInsteadOfEmptyCollection : "http://codenarc.sourceforge.net/codenarc-rules-design.html#ReturnsNullInsteadOfEmptyCollection",
    SimpleDateFormatMissingLocale : "http://codenarc.sourceforge.net/codenarc-rules-design.html#SimpleDateFormatMissingLocale",
    StatelessSingleton : "http://codenarc.sourceforge.net/codenarc-rules-design.html#StatelessSingleton",
    ToStringReturnsNull : "http://codenarc.sourceforge.net/codenarc-rules-design.html#ToStringReturnsNull",
    DuplicateListLiteral : "http://codenarc.sourceforge.net/codenarc-rules-dry.html#DuplicateListLiteral",
    DuplicateMapLiteral : "http://codenarc.sourceforge.net/codenarc-rules-dry.html#DuplicateMapLiteral",
    DuplicateNumberLiteral : "http://codenarc.sourceforge.net/codenarc-rules-dry.html#DuplicateNumberLiteral",
    DuplicateStringLiteral : "http://codenarc.sourceforge.net/codenarc-rules-dry.html#DuplicateStringLiteral",
    CloneWithoutCloneable : "http://codenarc.sourceforge.net/codenarc-rules-enhanced.html#CloneWithoutCloneable",
    JUnitAssertEqualsConstantActualValue : "http://codenarc.sourceforge.net/codenarc-rules-enhanced.html#JUnitAssertEqualsConstantActualValue",
    MissingOverrideAnnotation : "http://codenarc.sourceforge.net/codenarc-rules-enhanced.html#MissingOverrideAnnotation",
    UnsafeImplementationAsMap : "http://codenarc.sourceforge.net/codenarc-rules-enhanced.html#UnsafeImplementationAsMap",
    CatchArrayIndexOutOfBoundsException : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#CatchArrayIndexOutOfBoundsException",
    CatchError : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#CatchError",
    CatchException : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#CatchException",
    CatchIllegalMonitorStateException : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#CatchIllegalMonitorStateException",
    CatchIndexOutOfBoundsException : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#CatchIndexOutOfBoundsException",
    CatchNullPointerException : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#CatchNullPointerException",
    CatchRuntimeException : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#CatchRuntimeException",
    CatchThrowable : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#CatchThrowable",
    ConfusingClassNamedException : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#ConfusingClassNamedException",
    ExceptionExtendsError : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#ExceptionExtendsError",
    ExceptionExtendsThrowable : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#ExceptionExtendsThrowable",
    ExceptionNotThrown : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#ExceptionNotThrown",
    MissingNewInThrowStatement : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#MissingNewInThrowStatement",
    ReturnNullFromCatchBlock : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#ReturnNullFromCatchBlock",
    SwallowThreadDeath : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#SwallowThreadDeath",
    ThrowError : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#ThrowError",
    ThrowException : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#ThrowException",
    ThrowNullPointerException : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#ThrowNullPointerException",
    ThrowRuntimeException : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#ThrowRuntimeException",
    ThrowThrowable : "http://codenarc.sourceforge.net/codenarc-rules-exceptions.html#ThrowThrowable",
    BlankLineBeforePackage : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#BlankLineBeforePackage",
    BlockEndsWithBlankLine : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#BlockEndsWithBlankLine",
    BlockStartsWithBlankLine : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#BlockStartsWithBlankLine",
    BracesForClass : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#BracesForClass",
    BracesForForLoop : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#BracesForForLoop",
    BracesForIfElse : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#BracesForIfElse",
    BracesForMethod : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#BracesForMethod",
    BracesForTryCatchFinally : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#BracesForTryCatchFinally",
    ClassJavadoc : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#ClassJavadoc",
    ClosureStatementOnOpeningLineOfMultipleLineClosure : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#ClosureStatementOnOpeningLineOfMultipleLineClosure",
    ConsecutiveBlankLines : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#ConsecutiveBlankLines",
    FileEndsWithoutNewline : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#FileEndsWithoutNewline",
    Indentation : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#Indentation",
    LineLength : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#LineLength",
    MissingBlankLineAfterImports : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#MissingBlankLineAfterImports",
    MissingBlankLineAfterPackage : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#MissingBlankLineAfterPackage",
    SpaceAfterCatch : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAfterCatch",
    SpaceAfterClosingBrace : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAfterClosingBrace",
    SpaceAfterComma : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAfterComma",
    SpaceAfterFor : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAfterFor",
    SpaceAfterIf : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAfterIf",
    SpaceAfterOpeningBrace : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAfterOpeningBrace",
    SpaceAfterSemicolon : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAfterSemicolon",
    SpaceAfterSwitch : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAfterSwitch",
    SpaceAfterWhile : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAfterWhile",
    SpaceAroundClosureArrow : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAroundClosureArrow",
    SpaceAroundMapEntryColon : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAroundMapEntryColon",
    SpaceAroundOperator : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceAroundOperator",
    SpaceBeforeClosingBrace : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceBeforeClosingBrace",
    SpaceBeforeOpeningBrace : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#SpaceBeforeOpeningBrace",
    TrailingWhitespace : "http://codenarc.sourceforge.net/codenarc-rules-formatting.html#TrailingWhitespace",
    IllegalClassMember : "http://codenarc.sourceforge.net/codenarc-rules-generic.html#IllegalClassMember",
    IllegalClassReference : "http://codenarc.sourceforge.net/codenarc-rules-generic.html#IllegalClassReference",
    IllegalPackageReference : "http://codenarc.sourceforge.net/codenarc-rules-generic.html#IllegalPackageReference",
    IllegalRegex : "http://codenarc.sourceforge.net/codenarc-rules-generic.html#IllegalRegex",
    IllegalString : "http://codenarc.sourceforge.net/codenarc-rules-generic.html#IllegalString",
    IllegalSubclass : "http://codenarc.sourceforge.net/codenarc-rules-generic.html#IllegalSubclass",
    RequiredRegex : "http://codenarc.sourceforge.net/codenarc-rules-generic.html#RequiredRegex",
    RequiredString : "http://codenarc.sourceforge.net/codenarc-rules-generic.html#RequiredString",
    StatelessClass : "http://codenarc.sourceforge.net/codenarc-rules-generic.html#StatelessClass",
    GrailsDomainHasEquals : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsDomainHasEquals",
    GrailsDomainHasToString : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsDomainHasToString",
    GrailsDomainReservedSqlKeywordName : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsDomainReservedSqlKeywordName",
    GrailsDomainStringPropertyMaxSize : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsDomainStringPropertyMaxSize",
    GrailsDomainWithServiceReference : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsDomainWithServiceReference",
    GrailsDuplicateConstraint : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsDuplicateConstraint",
    GrailsDuplicateMapping : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsDuplicateMapping",
    GrailsMassAssignment : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsMassAssignment",
    GrailsPublicControllerMethod : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsPublicControllerMethod",
    GrailsServletContextReference : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsServletContextReference",
    GrailsStatelessService : "http://codenarc.sourceforge.net/codenarc-rules-grails.html#GrailsStatelessService",
    AssignCollectionSort : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#AssignCollectionSort",
    AssignCollectionUnique : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#AssignCollectionUnique",
    ClosureAsLastMethodParameter : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ClosureAsLastMethodParameter",
    CollectAllIsDeprecated : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#CollectAllIsDeprecated",
    ConfusingMultipleReturns : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ConfusingMultipleReturns",
    ExplicitArrayListInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitArrayListInstantiation",
    ExplicitCallToAndMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToAndMethod",
    ExplicitCallToCompareToMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToCompareToMethod",
    ExplicitCallToDivMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToDivMethod",
    ExplicitCallToEqualsMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToEqualsMethod",
    ExplicitCallToGetAtMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToGetAtMethod",
    ExplicitCallToLeftShiftMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToLeftShiftMethod",
    ExplicitCallToMinusMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToMinusMethod",
    ExplicitCallToModMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToModMethod",
    ExplicitCallToMultiplyMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToMultiplyMethod",
    ExplicitCallToOrMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToOrMethod",
    ExplicitCallToPlusMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToPlusMethod",
    ExplicitCallToPowerMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToPowerMethod",
    ExplicitCallToRightShiftMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToRightShiftMethod",
    ExplicitCallToXorMethod : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitCallToXorMethod",
    ExplicitHashMapInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitHashMapInstantiation",
    ExplicitHashSetInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitHashSetInstantiation",
    ExplicitLinkedHashMapInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitLinkedHashMapInstantiation",
    ExplicitLinkedListInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitLinkedListInstantiation",
    ExplicitStackInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitStackInstantiation",
    ExplicitTreeSetInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#ExplicitTreeSetInstantiation",
    GStringAsMapKey : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#GStringAsMapKey",
    GStringExpressionWithinString : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#GStringExpressionWithinString",
    GetterMethodCouldBeProperty : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#GetterMethodCouldBeProperty",
    GroovyLangImmutable : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#GroovyLangImmutable",
    UseCollectMany : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#UseCollectMany",
    UseCollectNested : "http://codenarc.sourceforge.net/codenarc-rules-groovyism.html#UseCollectNested",
    DuplicateImport : "http://codenarc.sourceforge.net/codenarc-rules-imports.html#DuplicateImport",
    ImportFromSamePackage : "http://codenarc.sourceforge.net/codenarc-rules-imports.html#ImportFromSamePackage",
    ImportFromSunPackages : "http://codenarc.sourceforge.net/codenarc-rules-imports.html#ImportFromSunPackages",
    MisorderedStaticImports : "http://codenarc.sourceforge.net/codenarc-rules-imports.html#MisorderedStaticImports",
    NoWildcardImports : "http://codenarc.sourceforge.net/codenarc-rules-imports.html#NoWildcardImports",
    UnnecessaryGroovyImport : "http://codenarc.sourceforge.net/codenarc-rules-imports.html#UnnecessaryGroovyImport",
    UnusedImport : "http://codenarc.sourceforge.net/codenarc-rules-imports.html#UnusedImport",
    DirectConnectionManagement : "http://codenarc.sourceforge.net/codenarc-rules-jdbc.html#DirectConnectionManagement",
    JdbcConnectionReference : "http://codenarc.sourceforge.net/codenarc-rules-jdbc.html#JdbcConnectionReference",
    JdbcResultSetReference : "http://codenarc.sourceforge.net/codenarc-rules-jdbc.html#JdbcResultSetReference",
    JdbcStatementReference : "http://codenarc.sourceforge.net/codenarc-rules-jdbc.html#JdbcStatementReference",
    ChainedTest : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#ChainedTest",
    CoupledTestCase : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#CoupledTestCase",
    JUnitAssertAlwaysFails : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitAssertAlwaysFails",
    JUnitAssertAlwaysSucceeds : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitAssertAlwaysSucceeds",
    JUnitFailWithoutMessage : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitFailWithoutMessage",
    JUnitLostTest : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitLostTest",
    JUnitPublicField : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitPublicField",
    JUnitPublicNonTestMethod : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitPublicNonTestMethod",
    JUnitPublicProperty : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitPublicProperty",
    JUnitSetUpCallsSuper : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitSetUpCallsSuper",
    JUnitStyleAssertions : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitStyleAssertions",
    JUnitTearDownCallsSuper : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitTearDownCallsSuper",
    JUnitTestMethodWithoutAssert : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitTestMethodWithoutAssert",
    JUnitUnnecessarySetUp : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitUnnecessarySetUp",
    JUnitUnnecessaryTearDown : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitUnnecessaryTearDown",
    JUnitUnnecessaryThrowsException : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#JUnitUnnecessaryThrowsException",
    SpockIgnoreRestUsed : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#SpockIgnoreRestUsed",
    UnnecessaryFail : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#UnnecessaryFail",
    UseAssertEqualsInsteadOfAssertTrue : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#UseAssertEqualsInsteadOfAssertTrue",
    UseAssertFalseInsteadOfNegation : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#UseAssertFalseInsteadOfNegation",
    UseAssertNullInsteadOfAssertEquals : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#UseAssertNullInsteadOfAssertEquals",
    UseAssertSameInsteadOfAssertTrue : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#UseAssertSameInsteadOfAssertTrue",
    UseAssertTrueInsteadOfAssertEquals : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#UseAssertTrueInsteadOfAssertEquals",
    UseAssertTrueInsteadOfNegation : "http://codenarc.sourceforge.net/codenarc-rules-junit.html#UseAssertTrueInsteadOfNegation",
    LoggerForDifferentClass : "http://codenarc.sourceforge.net/codenarc-rules-logging.html#LoggerForDifferentClass",
    LoggerWithWrongModifiers : "http://codenarc.sourceforge.net/codenarc-rules-logging.html#LoggerWithWrongModifiers",
    LoggingSwallowsStacktrace : "http://codenarc.sourceforge.net/codenarc-rules-logging.html#LoggingSwallowsStacktrace",
    MultipleLoggers : "http://codenarc.sourceforge.net/codenarc-rules-logging.html#MultipleLoggers",
    PrintStackTrace : "http://codenarc.sourceforge.net/codenarc-rules-logging.html#PrintStackTrace",
    Println : "http://codenarc.sourceforge.net/codenarc-rules-logging.html#Println",
    SystemErrPrint : "http://codenarc.sourceforge.net/codenarc-rules-logging.html#SystemErrPrint",
    SystemOutPrint : "http://codenarc.sourceforge.net/codenarc-rules-logging.html#SystemOutPrint",
    AbstractClassName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#AbstractClassName",
    ClassName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#ClassName",
    ClassNameSameAsFilename : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#ClassNameSameAsFilename",
    ClassNameSameAsSuperclass : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#ClassNameSameAsSuperclass",
    ConfusingMethodName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#ConfusingMethodName",
    FactoryMethodName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#FactoryMethodName",
    FieldName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#FieldName",
    InterfaceName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#InterfaceName",
    InterfaceNameSameAsSuperInterface : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#InterfaceNameSameAsSuperInterface",
    MethodName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#MethodName",
    ObjectOverrideMisspelledMethodName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#ObjectOverrideMisspelledMethodName",
    PackageName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#PackageName",
    PackageNameMatchesFilePath : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#PackageNameMatchesFilePath",
    ParameterName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#ParameterName",
    PropertyName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#PropertyName",
    VariableName : "http://codenarc.sourceforge.net/codenarc-rules-naming.html#VariableName",
    FileCreateTempFile : "http://codenarc.sourceforge.net/codenarc-rules-security.html#FileCreateTempFile",
    InsecureRandom : "http://codenarc.sourceforge.net/codenarc-rules-security.html#InsecureRandom",
    JavaIoPackageAccess : "http://codenarc.sourceforge.net/codenarc-rules-security.html#JavaIoPackageAccess",
    NonFinalPublicField : "http://codenarc.sourceforge.net/codenarc-rules-security.html#NonFinalPublicField",
    NonFinalSubclassOfSensitiveInterface : "http://codenarc.sourceforge.net/codenarc-rules-security.html#NonFinalSubclassOfSensitiveInterface",
    ObjectFinalize : "http://codenarc.sourceforge.net/codenarc-rules-security.html#ObjectFinalize",
    PublicFinalizeMethod : "http://codenarc.sourceforge.net/codenarc-rules-security.html#PublicFinalizeMethod",
    SystemExit : "http://codenarc.sourceforge.net/codenarc-rules-security.html#SystemExit",
    UnsafeArrayDeclaration : "http://codenarc.sourceforge.net/codenarc-rules-security.html#UnsafeArrayDeclaration",
    EnumCustomSerializationIgnored : "http://codenarc.sourceforge.net/codenarc-rules-serialization.html#EnumCustomSerializationIgnored",
    SerialPersistentFields : "http://codenarc.sourceforge.net/codenarc-rules-serialization.html#SerialPersistentFields",
    SerialVersionUID : "http://codenarc.sourceforge.net/codenarc-rules-serialization.html#SerialVersionUID",
    SerializableClassMustDefineSerialVersionUID : "http://codenarc.sourceforge.net/codenarc-rules-serialization.html#SerializableClassMustDefineSerialVersionUID",
    AbcMetric : "http://codenarc.sourceforge.net/codenarc-rules-size.html#AbcMetric",
    ClassSize : "http://codenarc.sourceforge.net/codenarc-rules-size.html#ClassSize",
    CrapMetric : "http://codenarc.sourceforge.net/codenarc-rules-size.html#CrapMetric",
    CyclomaticComplexity : "http://codenarc.sourceforge.net/codenarc-rules-size.html#CyclomaticComplexity",
    MethodCount : "http://codenarc.sourceforge.net/codenarc-rules-size.html#MethodCount",
    MethodSize : "http://codenarc.sourceforge.net/codenarc-rules-size.html#MethodSize",
    NestedBlockDepth : "http://codenarc.sourceforge.net/codenarc-rules-size.html#NestedBlockDepth",
    ParameterCount : "http://codenarc.sourceforge.net/codenarc-rules-size.html#ParameterCount",
    AddEmptyString : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#AddEmptyString",
    ConsecutiveLiteralAppends : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#ConsecutiveLiteralAppends",
    ConsecutiveStringConcatenation : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#ConsecutiveStringConcatenation",
    UnnecessaryBigDecimalInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryBigDecimalInstantiation",
    UnnecessaryBigIntegerInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryBigIntegerInstantiation",
    UnnecessaryBooleanExpression : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryBooleanExpression",
    UnnecessaryBooleanInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryBooleanInstantiation",
    UnnecessaryCallForLastElement : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryCallForLastElement",
    UnnecessaryCallToSubstring : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryCallToSubstring",
    UnnecessaryCast : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryCast",
    UnnecessaryCatchBlock : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryCatchBlock",
    UnnecessaryCollectCall : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryCollectCall",
    UnnecessaryCollectionCall : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryCollectionCall",
    UnnecessaryConstructor : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryConstructor",
    UnnecessaryDefInFieldDeclaration : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryDefInFieldDeclaration",
    UnnecessaryDefInMethodDeclaration : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryDefInMethodDeclaration",
    UnnecessaryDefInVariableDeclaration : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryDefInVariableDeclaration",
    UnnecessaryDotClass : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryDotClass",
    UnnecessaryDoubleInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryDoubleInstantiation",
    UnnecessaryElseStatement : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryElseStatement",
    UnnecessaryFinalOnPrivateMethod : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryFinalOnPrivateMethod",
    UnnecessaryFloatInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryFloatInstantiation",
    UnnecessaryGString : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryGString",
    UnnecessaryGetter : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryGetter",
    UnnecessaryIfStatement : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryIfStatement",
    UnnecessaryInstanceOfCheck : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryInstanceOfCheck",
    UnnecessaryInstantiationToGetClass : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryInstantiationToGetClass",
    UnnecessaryIntegerInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryIntegerInstantiation",
    UnnecessaryLongInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryLongInstantiation",
    UnnecessaryModOne : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryModOne",
    UnnecessaryNullCheck : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryNullCheck",
    UnnecessaryNullCheckBeforeInstanceOf : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryNullCheckBeforeInstanceOf",
    UnnecessaryObjectReferences : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryObjectReferences",
    UnnecessaryOverridingMethod : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryOverridingMethod",
    UnnecessaryPackageReference : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryPackageReference",
    UnnecessaryParenthesesForMethodCallWithClosure : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryParenthesesForMethodCallWithClosure",
    UnnecessaryPublicModifier : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryPublicModifier",
    UnnecessaryReturnKeyword : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryReturnKeyword",
    UnnecessarySafeNavigationOperator : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessarySafeNavigationOperator",
    UnnecessarySelfAssignment : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessarySelfAssignment",
    UnnecessarySemicolon : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessarySemicolon",
    UnnecessarySetter : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessarySetter",
    UnnecessaryStringInstantiation : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryStringInstantiation",
    UnnecessarySubstring : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessarySubstring",
    UnnecessaryTernaryExpression : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryTernaryExpression",
    UnnecessaryToString : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryToString",
    UnnecessaryTransientModifier : "http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryTransientModifier",
    UnusedArray : "http://codenarc.sourceforge.net/codenarc-rules-unused.html#UnusedArray",
    UnusedMethodParameter : "http://codenarc.sourceforge.net/codenarc-rules-unused.html#UnusedMethodParameter",
    UnusedObject : "http://codenarc.sourceforge.net/codenarc-rules-unused.html#UnusedObject",
    UnusedPrivateField : "http://codenarc.sourceforge.net/codenarc-rules-unused.html#UnusedPrivateField",
    UnusedPrivateMethod : "http://codenarc.sourceforge.net/codenarc-rules-unused.html#UnusedPrivateMethod",
    UnusedPrivateMethodParameter : "http://codenarc.sourceforge.net/codenarc-rules-unused.html#UnusedPrivateMethodParameter",
    UnusedVariable : "http://codenarc.sourceforge.net/codenarc-rules-unused.html#UnusedVariable"
  ]

  @Override
  void writeReport(AnalysisContext analysisContext, Results results) {
    assert analysisContext
    assert results
    AnsiConsole.systemInstall();
    
    println()
    printFileViolations(results)
    println()

    AnsiConsole.systemUninstall();
  }

  protected void printFileViolations(Results results) {

    println ansi().fg(YELLOW).a("File: ${results.path}").reset()
    def violations = results.violations.findAll { v -> v.rule.priority <= maxPriority }
    if (violations.size() == 0) {
      println ansi().fg(GREEN).a("✓ Clean").reset()
    } else {
      violations.sort { violation -> violation.rule.priority }.each { violation ->
        println()
        def rule = violation.rule
        def message = violation.message
        def source = violation.sourceLine
        println "${ansi().fg(WHITE).a(violation.lineNumber).reset()} ${ansi().fg(BLUE).a(rule.name).reset()} (${getRuleUrl(rule.name)})"
        if (message) {
          println "  ${message}"
        }
        if (source) {
          println "  ${ansi().fg(CYAN).a(source).reset()}"
        }
      }
    }
    println()
  }

  private String getRuleUrl(String name) {
    return ruleToUrl[name]
  }
}
