#!/bin/bash -eu
project_root="$(cd $(dirname ${BASH_SOURCE[0]}); cd ..; pwd)"
source "$project_root/libexec/setup-env.sh"

usage="
groovy-lint [-h][-w][-r <path>] <file>[,<file>...]
 -h         help
 -w         watch
 -r <path>  specifies rules.groovy file. Defaults to using all rules.

Pass in the files you want and they will be linted.
"
watch=false
rules_classpath=
rules_filename=
while getopts ":hwr:" opt; do
  case "$opt" in
    h) echo "$usage"; exit;;
    w) watch=true;;
    r)
      rules_classpath="$(dirname "$OPTARG")"
      rules_filename="$(basename "$OPTARG")"
    ;;
  esac
done
shift $(( OPTIND - 1 ))


my_writer_jar="$project_root/lib/CliConsoleReportWriter.jar"
my_runner_jar="$project_root/lib/CliCodeNarc.jar"

# probably should do something different with the config...
classpath+=":$my_runner_jar:$my_writer_jar:$project_root/lib"
if [[ "$rules_classpath" ]]; then
  classpath="$rules_classpath:$classpath"
fi

args="$@"
if [[ $watch ]]; then
  args="-w $args"
fi
if [[ $rules_filename ]]; then
  args="-r \"$rules_filename\" $args"
fi
java -classpath "$classpath" CliCodeNarc $args
